jsf-events/src/ru/edu/asu/jsf/MyBean.java
package ru.edu.asu.jsf;

import java.io.Serializable;

import javax.faces.event.ActionEvent;
import javax.faces.event.ValueChangeEvent;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

@Named
@ViewScoped
public class MyBean implements Serializable {

	private boolean inputEnabled = false;
	private boolean modeNames = true;
	private SelectItem[] citiesNames = {
		new SelectItem("Moscow"),
		new SelectItem("Astrakhan"),
		new SelectItem("Volgograd")
	};
	private SelectItem[] citiesCodes = {
			new SelectItem("495"),
			new SelectItem("8512"),
			new SelectItem("8412")
		};
	
	private String selectedCity;
	
	public String getSelectedCity() {
		return selectedCity;
	}

	public void setSelectedCity(String selectedCity) {
		this.selectedCity = selectedCity;
	}

	public boolean isInputEnabled() {
		return inputEnabled;
	}

	public void setInputEnabled(boolean inputEnabled) {
		this.inputEnabled = inputEnabled;
	}

	public boolean isModeNames() {
		return modeNames;
	}

	public void setModeNames(boolean modeNames) {
		this.modeNames = modeNames;
	}

	public SelectItem[] getCities() {
		if (isModeNames())
			return citiesNames;
		else
			return citiesCodes;
	}

	public void toggleInput(ActionEvent event) {
		inputEnabled = !inputEnabled;
	}
	
	public void modeChanged(ValueChangeEvent event) {
		modeNames = ((Boolean)event.getNewValue()).booleanValue();
	}
	
	public String inputComplete() {
		return "";
	}
}

jsf-events/WebContent/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<body>
	<f:view>
		<h:form>
			<h:commandButton value="ToggleInput" actionListener="#{myBean.toggleInput}"
				immediate="true" />
			<h:selectBooleanCheckbox valueChangeListener="#{myBean.modeChanged}"
				immediate="true" onchange="submit()">
					Показать названия городов
			</h:selectBooleanCheckbox>
			<h:selectOneListbox value="#{myBean.selectedCity}" disabled="#{!myBean.inputEnabled}">
				<f:selectItems value="#{myBean.cities}" />
			</h:selectOneListbox>
			<h:commandButton value="OK" action="#{myBean.inputComplete}" />
		</h:form>
		Выбрано: <h:outputText value="#{myBean.selectedCity}" />
	</f:view>
</body>
</html>

jsf-events/WebContent/result.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<body>
	<f:view>
		<h:outputText value="#{myBean.selectedCity}" />
	</f:view>
</body>
</html>